on:
  push:
name: update-pkgdown-site

jobs:
  update-pkgdown-site:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install linux dependencies
        run: |        
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev libnetcdf-dev libudunits2-dev libgdal-dev libharfbuzz-dev libfribidi-dev
        shell: bash
        
      - name: Install packages
        run: Rscript -e 'install.packages(c("pkgdown", "roxygen2", "knitr", "raster"))'

      - name: Update R function documentation
        run: Rscript -e 'roxygen2::roxygenize()'

      - name: Build site
        run: Rscript -e 'pkgdown::build_site()'

      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Commit all changes
        run: |
          git add -A && git commit -m 'Build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
